// lilydevadvHandlers.idl : IDL source for lilydevadvHandlers
//

// This file will be processed by the MIDL tool to
// produce the type library (lilydevadvHandlers.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(50333a37-235c-473d-b926-58c7e2c46c90),
	pointer_default(unique)
]
interface IPreview : IUnknown
{
};

[
	object,
	uuid(821f00ab-7ef9-41b7-9f51-4828af0f769c),
	pointer_default(unique)
]
interface IThumbnail : IUnknown
{
};

[
	object,
	uuid(b9f402fa-31e1-45a8-b20f-1e09c73b64c9),
	pointer_default(unique)
]
interface ISearch : IUnknown
{
};

[
	uuid(dd2cc231-c0ff-4ba8-8fa2-c5803fb949fa),
	version(1.0),
]
library lilydevadvHandlersLib
{
	importlib("stdole2.tlb");
	[
		uuid(4a91354c-e719-416c-ab81-935c024e7421)
	]
	coclass Preview
	{
		[default] interface IPreviewHandler;
	};
	[
		uuid(07e1972d-1157-49ec-a365-2d8b4e28ddb3)
	]
	coclass Thumbnail
	{
		[default] interface IThumbnailProvider;
	};
	[
		uuid(aad80e77-f98f-41d5-a600-64dbb0aa27ee)
	]
	coclass Search
	{
		[default] interface IFilter;
	};
};

import "shobjidl.idl";
import "thumbcache.idl";
import "filter.idl";
