//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fonder.Lilian.New.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreContent() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fonder.Lilian.New.Properties.CoreContent", typeof(CoreContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lilian can either compile a single script or an entire project. Press P to use a project file, or press S to use a single file..
        /// </summary>
        internal static string ChoiceScreenBody {
            get {
                return ResourceManager.GetString("ChoiceScreenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a project file.
        /// </summary>
        internal static string ChoiceScreenChoice1 {
            get {
                return ResourceManager.GetString("ChoiceScreenChoice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a single file.
        /// </summary>
        internal static string ChoiceScreenChoice2 {
            get {
                return ResourceManager.GetString("ChoiceScreenChoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  days .
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File does not exist!.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  hours .
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lilian has successfully compiled your program. Press any key to continue..
        /// </summary>
        internal static string Hurrah {
            get {
                return ResourceManager.GetString("Hurrah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à []=Continue.
        /// </summary>
        internal static string HurrahAny {
            get {
                return ResourceManager.GetString("HurrahAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where is the project file?.
        /// </summary>
        internal static string InputAskVer1 {
            get {
                return ResourceManager.GetString("InputAskVer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where is the code file?.
        /// </summary>
        internal static string InputAskVer2 {
            get {
                return ResourceManager.GetString("InputAskVer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid state for the environment. If you don&apos;t know what happened, it&apos;s my fault..
        /// </summary>
        internal static string Lamentation1 {
            get {
                return ResourceManager.GetString("Lamentation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The token &apos;{0}&apos; has an invalid predefined UUID. Leave the UUID field blank for a random one, or reformat your UUID..
        /// </summary>
        internal static string Lamentation10 {
            get {
                return ResourceManager.GetString("Lamentation10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. Something happened..
        /// </summary>
        internal static string Lamentation11 {
            get {
                return ResourceManager.GetString("Lamentation11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The opcode &apos;{0}&apos; does not exist. Did you forget to add the opcode first before using it?.
        /// </summary>
        internal static string Lamentation12 {
            get {
                return ResourceManager.GetString("Lamentation12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The predefined opcode &apos;{0}&apos; does not exist. Please reinstall Lilian, or send a bug report..
        /// </summary>
        internal static string Lamentation13 {
            get {
                return ResourceManager.GetString("Lamentation13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. Right bracket {0} for left bracket {1} does not exist. Did you forget to add the token first before using it?.
        /// </summary>
        internal static string Lamentation14 {
            get {
                return ResourceManager.GetString("Lamentation14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The opcode {0} does not exist. Did you forget to assign the operation to there?.
        /// </summary>
        internal static string Lamentation15 {
            get {
                return ResourceManager.GetString("Lamentation15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. Sentence {0} has more pointers than the allocated parameters for the associated opcode {1} &apos;{2}&apos;..
        /// </summary>
        internal static string Lamentation16 {
            get {
                return ResourceManager.GetString("Lamentation16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File operation error. {0}.
        /// </summary>
        internal static string Lamentation17 {
            get {
                return ResourceManager.GetString("Lamentation17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File operation error. The archive &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Lamentation18 {
            get {
                return ResourceManager.GetString("Lamentation18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File operation error. Cannot export to an archive. This is not your fault; it&apos;s ours. Contact us lmao. ({0}).
        /// </summary>
        internal static string Lamentation19 {
            get {
                return ResourceManager.GetString("Lamentation19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syntax error. A string was never terminated..
        /// </summary>
        internal static string Lamentation2 {
            get {
                return ResourceManager.GetString("Lamentation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File operation error. Cannot import from an archive. Either that you&apos;re a dumbarse and imported something not in an LPS format or it&apos;s our fault. If so, contact us. lMAO. ({0}).
        /// </summary>
        internal static string Lamentation20 {
            get {
                return ResourceManager.GetString("Lamentation20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The sentence structure &apos;{0}&apos; does not correspond with any of the available statements..
        /// </summary>
        internal static string Lamentation21 {
            get {
                return ResourceManager.GetString("Lamentation21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Handshake with Coco failed. {0}.
        /// </summary>
        internal static string Lamentation22 {
            get {
                return ResourceManager.GetString("Lamentation22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is an undefined feature in this version. Use a newer version of Lilian..
        /// </summary>
        internal static string Lamentation23 {
            get {
                return ResourceManager.GetString("Lamentation23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stack error. {0}.
        /// </summary>
        internal static string Lamentation24 {
            get {
                return ResourceManager.GetString("Lamentation24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} does not exist in the current context..
        /// </summary>
        internal static string Lamentation25 {
            get {
                return ResourceManager.GetString("Lamentation25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid Int32 value..
        /// </summary>
        internal static string Lamentation26 {
            get {
                return ResourceManager.GetString("Lamentation26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index {0} goes beyond the current stream..
        /// </summary>
        internal static string Lamentation27 {
            get {
                return ResourceManager.GetString("Lamentation27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index {0} is in an incorrect format..
        /// </summary>
        internal static string Lamentation28 {
            get {
                return ResourceManager.GetString("Lamentation28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot be shrunk further..
        /// </summary>
        internal static string Lamentation29 {
            get {
                return ResourceManager.GetString("Lamentation29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syntax error. The pattern &apos;{0}&apos; does not exist in the current context..
        /// </summary>
        internal static string Lamentation3 {
            get {
                return ResourceManager.GetString("Lamentation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot be grown further..
        /// </summary>
        internal static string Lamentation30 {
            get {
                return ResourceManager.GetString("Lamentation30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot shrink a string!.
        /// </summary>
        internal static string Lamentation31 {
            get {
                return ResourceManager.GetString("Lamentation31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot grow a string!.
        /// </summary>
        internal static string Lamentation32 {
            get {
                return ResourceManager.GetString("Lamentation32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot shrink a character!.
        /// </summary>
        internal static string Lamentation33 {
            get {
                return ResourceManager.GetString("Lamentation33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot grow a character!.
        /// </summary>
        internal static string Lamentation34 {
            get {
                return ResourceManager.GetString("Lamentation34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot shrink whatever this is!.
        /// </summary>
        internal static string Lamentation35 {
            get {
                return ResourceManager.GetString("Lamentation35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot grow whatever this is!.
        /// </summary>
        internal static string Lamentation36 {
            get {
                return ResourceManager.GetString("Lamentation36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos;: cannot realise this string into an integral value..
        /// </summary>
        internal static string Lamentation37 {
            get {
                return ResourceManager.GetString("Lamentation37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following call doesn&apos;t lead to anywhere: &apos;{0}&apos;..
        /// </summary>
        internal static string Lamentation38 {
            get {
                return ResourceManager.GetString("Lamentation38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internal error: {0} {1}.
        /// </summary>
        internal static string Lamentation39 {
            get {
                return ResourceManager.GetString("Lamentation39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Lamentation4 {
            get {
                return ResourceManager.GetString("Lamentation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I&apos;ve just got a letter. &apos;{0}&apos;.
        /// </summary>
        internal static string Lamentation40 {
            get {
                return ResourceManager.GetString("Lamentation40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à aYO wat the fuk! Lamentation no. {0} does not exist!!!.
        /// </summary>
        internal static string Lamentation41 {
            get {
                return ResourceManager.GetString("Lamentation41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hi!.
        /// </summary>
        internal static string Lamentation42 {
            get {
                return ResourceManager.GetString("Lamentation42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Invalid build number..
        /// </summary>
        internal static string Lamentation43 {
            get {
                return ResourceManager.GetString("Lamentation43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. The project does not use this version of Lilian. Use at least {0}..
        /// </summary>
        internal static string Lamentation44 {
            get {
                return ResourceManager.GetString("Lamentation44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Unknown directive..
        /// </summary>
        internal static string Lamentation45 {
            get {
                return ResourceManager.GetString("Lamentation45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Unknown symbol &apos;{0}&apos;..
        /// </summary>
        internal static string Lamentation46 {
            get {
                return ResourceManager.GetString("Lamentation46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Cannot redefine the previous &apos;if&apos; statement..
        /// </summary>
        internal static string Lamentation47 {
            get {
                return ResourceManager.GetString("Lamentation47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. There was no &apos;if&apos; statement to attach this &apos;else&apos; statement to..
        /// </summary>
        internal static string Lamentation48 {
            get {
                return ResourceManager.GetString("Lamentation48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. There was no &apos;if&apos; statement to attach this &apos;elseif&apos; statement to..
        /// </summary>
        internal static string Lamentation49 {
            get {
                return ResourceManager.GetString("Lamentation49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The token &apos;{0}&apos; does not exist. Did you forget to add the token first before using it?.
        /// </summary>
        internal static string Lamentation5 {
            get {
                return ResourceManager.GetString("Lamentation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. There was no &apos;if&apos; statement to terminate..
        /// </summary>
        internal static string Lamentation50 {
            get {
                return ResourceManager.GetString("Lamentation50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. &apos;{0}&apos; already exists. Use &apos;defifn&apos; if needed..
        /// </summary>
        internal static string Lamentation51 {
            get {
                return ResourceManager.GetString("Lamentation51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. &apos;{0}&apos; does not exist. Use &apos;undefife&apos; if needed..
        /// </summary>
        internal static string Lamentation52 {
            get {
                return ResourceManager.GetString("Lamentation52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internal error. There is no more memory to work with on this compilation..
        /// </summary>
        internal static string Lamentation53 {
            get {
                return ResourceManager.GetString("Lamentation53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Lamentation54 {
            get {
                return ResourceManager.GetString("Lamentation54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. There are references to the following inexistent symbols: {0}..
        /// </summary>
        internal static string Lamentation55 {
            get {
                return ResourceManager.GetString("Lamentation55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internal error. For this version of Lilian, you cannot declare types other than the standard 15 .NET types..
        /// </summary>
        internal static string Lamentation56 {
            get {
                return ResourceManager.GetString("Lamentation56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The core grammar does not exist. Fall back to assembly syntax, or reinstall Lilian..
        /// </summary>
        internal static string Lamentation57 {
            get {
                return ResourceManager.GetString("Lamentation57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. We do not use dot-directives anymore. Use slash directives or fall back to Lilian 1.1..
        /// </summary>
        internal static string Lamentation58 {
            get {
                return ResourceManager.GetString("Lamentation58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Cannot declare a project inside of another..
        /// </summary>
        internal static string Lamentation59 {
            get {
                return ResourceManager.GetString("Lamentation59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. The predefined token &apos;{0}&apos; does not exist. Please reinstall Lilian, or send a bug report..
        /// </summary>
        internal static string Lamentation6 {
            get {
                return ResourceManager.GetString("Lamentation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Another project was already defined..
        /// </summary>
        internal static string Lamentation60 {
            get {
                return ResourceManager.GetString("Lamentation60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Cannot declare code macros in a project definition..
        /// </summary>
        internal static string Lamentation61 {
            get {
                return ResourceManager.GetString("Lamentation61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. If you were thinking that the &apos;include&apos; command adds a code file in that location, you were wrong. Do not use this command outside a project definition..
        /// </summary>
        internal static string Lamentation62 {
            get {
                return ResourceManager.GetString("Lamentation62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Cannot use this command outside of a project definition..
        /// </summary>
        internal static string Lamentation63 {
            get {
                return ResourceManager.GetString("Lamentation63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Cannot declare a grammar inside of another..
        /// </summary>
        internal static string Lamentation64 {
            get {
                return ResourceManager.GetString("Lamentation64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Another grammar was already defined..
        /// </summary>
        internal static string Lamentation65 {
            get {
                return ResourceManager.GetString("Lamentation65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing error. Cannot put this command in the current context..
        /// </summary>
        internal static string Lamentation66 {
            get {
                return ResourceManager.GetString("Lamentation66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; is an invalid type entered for this property. Define this type first, or contact me in the case of the default types..
        /// </summary>
        internal static string Lamentation67 {
            get {
                return ResourceManager.GetString("Lamentation67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Lamentation68 {
            get {
                return ResourceManager.GetString("Lamentation68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This parameter&apos;s type ({0}) does not correspond with that of &apos;{1}&apos; ({2}). Reorder your parameters in the stack or change the type..
        /// </summary>
        internal static string Lamentation69 {
            get {
                return ResourceManager.GetString("Lamentation69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. There can be nothing at token {0} because the {1} sentence only has {2}..
        /// </summary>
        internal static string Lamentation7 {
            get {
                return ResourceManager.GetString("Lamentation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is nothing on the tray to substitute the exclamation mark..
        /// </summary>
        internal static string Lamentation70 {
            get {
                return ResourceManager.GetString("Lamentation70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property &apos;{0}&apos; does not exist for type &apos;{1}&apos;..
        /// </summary>
        internal static string Lamentation71 {
            get {
                return ResourceManager.GetString("Lamentation71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This object&apos;s type ({0}) does not correspond with that of &apos;{1}&apos; ({2}). Change the type..
        /// </summary>
        internal static string Lamentation72 {
            get {
                return ResourceManager.GetString("Lamentation72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Lamentation73 {
            get {
                return ResourceManager.GetString("Lamentation73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not use &apos;store&apos; for the placement of structures to the store. Use &apos;put&apos; instead..
        /// </summary>
        internal static string Lamentation74 {
            get {
                return ResourceManager.GetString("Lamentation74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot perform arithmetic on these types yet. Tangible subroutines don&apos;t exist yet..
        /// </summary>
        internal static string Lamentation75 {
            get {
                return ResourceManager.GetString("Lamentation75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implementation error. Some tokens of the {0} sentence have already been specified..
        /// </summary>
        internal static string Lamentation8 {
            get {
                return ResourceManager.GetString("Lamentation8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syntax error. The token &apos;{0}&apos; cannot exist in its current position of the {1} sentence..
        /// </summary>
        internal static string Lamentation9 {
            get {
                return ResourceManager.GetString("Lamentation9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linking named references....
        /// </summary>
        internal static string LinkingStatus {
            get {
                return ResourceManager.GetString("LinkingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  minutes .
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actually, no..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where should be the output? (Leave empty for the one found in the project&apos;s definition).
        /// </summary>
        internal static string OutputAsk {
            get {
                return ResourceManager.GetString("OutputAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait while Lilian examines your code. This may take several minutes depending on the size of the code..
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait while Lilian finalises the program..
        /// </summary>
        internal static string PleaseWaitFinal {
            get {
                return ResourceManager.GetString("PleaseWaitFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preprocessing the project....
        /// </summary>
        internal static string PreprocessStatus {
            get {
                return ResourceManager.GetString("PreprocessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue..
        /// </summary>
        internal static string PressAny {
            get {
                return ResourceManager.GetString("PressAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonder Lilian Language Environment.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oh dear, I&apos;ve made quite a mess. Press any key to continue..
        /// </summary>
        internal static string PSODFoot {
            get {
                return ResourceManager.GetString("PSODFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem occurred during execution. Meditation out of balance..
        /// </summary>
        internal static string PSODHead {
            get {
                return ResourceManager.GetString("PSODHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading.
        /// </summary>
        internal static string ReadingStatus {
            get {
                return ResourceManager.GetString("ReadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à remaining..
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  secondes .
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This programme is asking for a file..
        /// </summary>
        internal static string ThisProgIsAsk {
            get {
                return ResourceManager.GetString("ThisProgIsAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translating code to intermediate representation.
        /// </summary>
        internal static string TranslationStatus {
            get {
                return ResourceManager.GetString("TranslationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to run the program afterwards?.
        /// </summary>
        internal static string WannaRun {
            get {
                return ResourceManager.GetString("WannaRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This program will compile a project or script into an executable. Press Enter to continue to next page. Press F3 to exit..
        /// </summary>
        internal static string WelcomeScreenBody {
            get {
                return ResourceManager.GetString("WelcomeScreenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string WelcomeScreenChoice1 {
            get {
                return ResourceManager.GetString("WelcomeScreenChoice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string WelcomeScreenChoice2 {
            get {
                return ResourceManager.GetString("WelcomeScreenChoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the Lilian environment..
        /// </summary>
        internal static string WelcomeScreenHeader {
            get {
                return ResourceManager.GetString("WelcomeScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, please!.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
